

subdir-y := $(sort $(patsubst %/,%, $(filter %/, $(obj-y))))

obj-y		:= $(patsubst %/, %/built-in.a, $(obj-y))


# Expand $(foo-objs) $(foo-y) etc. by replacing their individuals
suffix-search = $(strip $(foreach s, $3, $($(1:%$(strip $2)=%$s))))
# List composite targets that are constructed by combining other targets
multi-search = $(sort $(foreach m, $1, $(if $(call suffix-search, $m, $2, $3 -), $m)))
# List primitive targets that are compiled from source files
real-search = $(foreach m, $1, $(if $(call suffix-search, $m, $2, $3 -), $(call suffix-search, $m, $2, $3), $m))

real-obj-y := $(call real-search, $(obj-y), .o, -objs -y)

obj-y := $(patsubst %/, %/built-in.a, $(obj-y))

ifneq ($(obj),.)
real-obj-y	:= $(addprefix $(obj)/,$(real-obj-y))
subdir-y	:= $(addprefix $(obj)/,$(subdir-y))
endif